[package]
name = "kvs"
version = "0.1.0"
authors = ["Parallaxis"]
description = "A key-value store"
edition = "2021"

[dependencies]
clap = "4.5.31"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.3"
clap = "4.5.31"